### ISSUE TITLE
Allow setting timeout value from env

### ISSUE THREAD

**Issue by ianardee** [mindee/mindee-api-dotnet#109]
Allow setting the request timeout from  `MINDEE_REQUEST_TIMEOUT` envvar.

**Comment by Kvindee** [comment]
That means when the request sent to Mindee exceed the value of MINDEE_REQUEST_TIMEOUT, it should do something.
What should the SDK do ? Throw a MindeeException for example ?

**Comment by ianardee** [comment]
Just use it set this value:
https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-7.0

BTW, default should be 120 seconds.
