### ISSUE TITLE
Cannot use custom endpoint

### ISSUE THREAD

**Issue by Drosos-kalyvas** [mindee/mindee-api-dotnet#209]
Following the instructions for .NET custom API setup listed here:
https://developers.mindee.com/docs/dotnet-api-builder
I am trying to make a call to parse an image but I get the following error: 
`Mindee.Exceptions.Mindee403ExceptionMindee API client: Forbidden.This product does not support synchronous mode `
Following the steps described here: 
https://developers.mindee.com/docs/prediction-asynchronous
I haven't managed to make it work with sending the document and getting back the prediction with polling.
Do you have any suggestsions for a solution?
Thank you

**Comment by sebastianMindee** [comment]
Hello, the type of APIs cited in the documentation is for the older generation of custom builds (API Builder). The support for the newer generation (DocTI) is planned for the short term, but not available on the .NET client library yet.

It should also be noted that DocTI only support async mode.

**Comment by Drosos-kalyvas** [comment]
Thanks for your quick response!

**Comment by Drosos-kalyvas** [comment]
I have been trying for the last two days to actually make it work with a POST then GET api calls to my custom endpoint but no matter what, my GET api call returns the "processing" status JSON. Any thoughts/suggestions on how should I set it up? 
I never get back a redirect status code with the prediction endpoint id.
```
// POST
var url = "https://api.mindee.net/v1/products/account/apiName/v1/predict_async";
var httpClient = new HttpClient();
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Token", apiKey);
var response = httpClient.PostAsync(url, form).Result;
var result = response.Content.ReadAsStringAsync().Result;
httpClient.Dispose();
JObject jsonRequestObject = JObject.Parse(result);
id = (string)jsonRequestObject["job"]["id"];

// GET
var httpClient = new HttpClient();
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Token", "apiKey");
var response = await httpClient.GetAsync($"https://api.mindee.net/v1/products/account/apiName/v1/documents/queue/{id}");

if (response.StatusCode == System.Net.HttpStatusCode.Found ||
    response.StatusCode == System.Net.HttpStatusCode.Redirect)
{
    var redirectedUrl = response.Headers.Location;

    response = await httpClient.GetAsync(redirectedUrl);
}

response.EnsureSuccessStatusCode();
var content = await response.Content.ReadAsStringAsync();
Console.WriteLine(content);
```

**Comment by ianardee** [comment]
Release [v3.11.0](https://github.com/mindee/mindee-api-dotnet/releases/tag/v3.11.0) adds support for generated documents.

Release  [v3.12.0](https://github.com/mindee/mindee-api-dotnet/releases/tag/v3.12.0) adds support for webhooks when using async APIs.
