### ISSUE TITLE
Exception Method not found in RestSharp dependency

### ISSUE THREAD

**Issue by olivierbachard** [mindee/mindee-api-dotnet#219]
When trying to instanciate a MindeeClient, I get the following error :
```System.MissingMethodException: Method not found: 'RestSharp.RestClient RestSharp.RestClientExtensions.AddDefaultHeaders(RestSharp.RestClient, System.Collections.Generic.Dictionary`2<System.String,System.String>)'.
         at Mindee.Http.MindeeApi..ctor(IOptions`1 mindeeSettings, ILogger`1 logger, HttpMessageHandler httpMessageHandler)
         at Mindee.MindeeClient..ctor(MindeeSettings mindeeSettings, ILoggerFactory logger)```

I tried to instanciate a client manually using `new MindeeClient("my-api-key")` and `new MindeeClient(<mindeeSettings>)` .
Mindee v3.13.0
RestSharp v110.2.0

Thank you for your help.

**Comment by olivierbachard** [comment]
By retrieving the code and upgrading RestSharp version to 110.2.0 it works, would it be possible to make a release with this version ? I have other projects using RestSharp 110.2.0 and cannot downgrade it.

**Comment by sebastianMindee** [comment]
Hello, it seems that we missed this, thank you for raising this. A patch will be rolled out with an upgrade to RestSharp 111.3.0 along with the next release. It shouldn't be much more than a couple of days.
